// <auto-generated />
using System;
using APITienda.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APITienda.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210502221440_migracionforanea")]
    partial class migracionforanea
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("APITienda.Models.Contacto", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("personaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaExpira")
                        .HasColumnType("datetime");

                    b.Property<int>("TipoContacto")
                        .HasColumnType("int");

                    b.Property<int>("UsoContacto")
                        .HasColumnType("int");

                    b.Property<string>("Valor")
                        .HasColumnType("text");

                    b.HasKey("Id", "personaId");

                    b.HasIndex("personaId");

                    b.ToTable("Contacto");
                });

            modelBuilder.Entity("APITienda.Models.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<string>("NroDoc")
                        .HasColumnType("text");

                    b.Property<string>("Sexo")
                        .HasColumnType("text");

                    b.Property<string>("TipoDoc")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Persona");
                });

            modelBuilder.Entity("APITienda.Models.Contacto", b =>
                {
                    b.HasOne("APITienda.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("personaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
